import { Room } from "./Room";

export const rooms: Room[] = [
  {
    id: 1,
    description: "Cozy single room with city view",
    price: 75,
    location: "New York",
    totalbeds: 1,
    totalrooms: 1,
  },
  {
    id: 2,
    description: "Spacious double room near the beach",
    price: 120,
    location: "Miami",
    totalbeds: 2,
    totalrooms: 1,
  },
  {
    id: 3,
    description: "Modern apartment with kitchen",
    price: 150,
    location: "Los Angeles",
    totalbeds: 2,
    totalrooms: 3,
  },
  {
    id: 4,
    description: "Family suite with balcony",
    price: 200,
    location: "Orlando",
    totalbeds: 4,
    totalrooms: 2,
  },
  {
    id: 5,
    description: "Luxury penthouse with skyline view",
    price: 400,
    location: "Chicago",
    totalbeds: 3,
    totalrooms: 5,
  },
  {
    id: 6,
    description: "Affordable shared dormitory",
    price: 25,
    location: "Austin",
    totalbeds: 8,
    totalrooms: 1,
  },
  {
    id: 7,
    description: "Private studio with garden access",
    price: 90,
    location: "San Francisco",
    totalbeds: 1,
    totalrooms: 1,
  },
  {
    id: 8,
    description: "Rustic cabin in the woods",
    price: 130,
    location: "Denver",
    totalbeds: 3,
    totalrooms: 2,
  },
  {
    id: 9,
    description: "Seaside villa with private pool",
    price: 500,
    location: "Honolulu",
    totalbeds: 6,
    totalrooms: 4,
  },
  {
    id: 10,
    description: "Minimalist loft downtown",
    price: 180,
    location: "Seattle",
    totalbeds: 2,
    totalrooms: 2,
  },
  {
    id: 11,
    description: "Historical home with antique decor",
    price: 220,
    location: "Boston",
    totalbeds: 4,
    totalrooms: 3,
  },
  {
    id: 12,
    description: "Bright room in shared apartment",
    price: 70,
    location: "Philadelphia",
    totalbeds: 1,
    totalrooms: 1,
  },
  {
    id: 13,
    description: "Charming bungalow in countryside",
    price: 140,
    location: "Nashville",
    totalbeds: 2,
    totalrooms: 2,
  },
  {
    id: 14,
    description: "Penthouse suite with jacuzzi",
    price: 600,
    location: "Las Vegas",
    totalbeds: 5,
    totalrooms: 4,
  },
  {
    id: 15,
    description: "Modern flat with rooftop access",
    price: 300,
    location: "San Diego",
    totalbeds: 3,
    totalrooms: 3,
  },
  {
    id: 16,
    description: "Quaint cottage with fireplace",
    price: 120,
    location: "Portland",
    totalbeds: 2,
    totalrooms: 2,
  },
  {
    id: 17,
    description: "Luxury chalet in the mountains",
    price: 450,
    location: "Aspen",
    totalbeds: 5,
    totalrooms: 3,
  },
  {
    id: 18,
    description: "Basic room in hostel",
    price: 20,
    location: "Salt Lake City",
    totalbeds: 12,
    totalrooms: 1,
  },
  {
    id: 19,
    description: "City center apartment with Wi-Fi",
    price: 190,
    location: "Dallas",
    totalbeds: 2,
    totalrooms: 2,
  },
  {
    id: 20,
    description: "Eco-friendly tiny house",
    price: 100,
    location: "Boulder",
    totalbeds: 1,
    totalrooms: 1,
  },
  {
    id: 21,
    description: "Chic duplex near shopping district",
    price: 250,
    location: "Atlanta",
    totalbeds: 3,
    totalrooms: 2,
  },
  {
    id: 22,
    description: "Treehouse with scenic views",
    price: 180,
    location: "Sedona",
    totalbeds: 2,
    totalrooms: 1,
  },
  {
    id: 23,
    description: "Artistic studio in creative hub",
    price: 95,
    location: "Austin",
    totalbeds: 1,
    totalrooms: 1,
  },
  {
    id: 24,
    description: "Lakefront cabin with dock access",
    price: 220,
    location: "Minneapolis",
    totalbeds: 3,
    totalrooms: 2,
  },
  {
    id: 25,
    description: "Renovated barn in rural area",
    price: 170,
    location: "Raleigh",
    totalbeds: 2,
    totalrooms: 2,
  },
  {
    id: 26,
    description: "Modern apartment with smart home features",
    price: 320,
    location: "San Jose",
    totalbeds: 3,
    totalrooms: 3,
  },
  {
    id: 27,
    description: "Large villa for family gatherings",
    price: 650,
    location: "Palm Springs",
    totalbeds: 8,
    totalrooms: 6,
  },
  {
    id: 28,
    description: "Budget room with shared amenities",
    price: 35,
    location: "Houston",
    totalbeds: 1,
    totalrooms: 1,
  },
  {
    id: 29,
    description: "Luxurious suite with concierge service",
    price: 700,
    location: "Manhattan",
    totalbeds: 4,
    totalrooms: 3,
  },
  {
    id: 30,
    description: "Peaceful retreat near hiking trails",
    price: 150,
    location: "Flagstaff",
    totalbeds: 3,
    totalrooms: 2,
  },
  {
    id: 31,
    description: "Charming houseboat on the water",
    price: 200,
    location: "Portland",
    totalbeds: 2,
    totalrooms: 2,
  },
  {
    id: 32,
    description: "Studio near university campus",
    price: 80,
    location: "Madison",
    totalbeds: 1,
    totalrooms: 1,
  },
  {
    id: 33,
    description: "Designer apartment with city skyline view",
    price: 300,
    location: "Los Angeles",
    totalbeds: 3,
    totalrooms: 2,
  },
  {
    id: 34,
    description: "Mountain lodge with ski-in access",
    price: 400,
    location: "Park City",
    totalbeds: 5,
    totalrooms: 3,
  },
  {
    id: 35,
    description: "Pet-friendly apartment with backyard",
    price: 160,
    location: "Sacramento",
    totalbeds: 2,
    totalrooms: 2,
  },
  {
    id: 36,
    description: "Single room in suburban home",
    price: 60,
    location: "Detroit",
    totalbeds: 1,
    totalrooms: 1,
  },
  {
    id: 37,
    description: "Historic cabin with modern upgrades",
    price: 240,
    location: "Bozeman",
    totalbeds: 3,
    totalrooms: 3,
  },
  {
    id: 38,
    description: "Downtown condo with parking included",
    price: 210,
    location: "Phoenix",
    totalbeds: 2,
    totalrooms: 2,
  },
  {
    id: 39,
    description: "Beach house with direct ocean access",
    price: 550,
    location: "Santa Monica",
    totalbeds: 4,
    totalrooms: 3,
  },
  {
    id: 40,
    description: "Chic flat in the arts district",
    price: 190,
    location: "New Orleans",
    totalbeds: 2,
    totalrooms: 2,
  },
  {
    id: 41,
    description: "Converted warehouse loft",
    price: 260,
    location: "Brooklyn",
    totalbeds: 3,
    totalrooms: 2,
  },
  {
    id: 42,
    description: "Simple room with free breakfast",
    price: 50,
    location: "Charlotte",
    totalbeds: 1,
    totalrooms: 1,
  },
  {
    id: 43,
    description: "Beachfront bungalow with hammocks",
    price: 400,
    location: "Key West",
    totalbeds: 2,
    totalrooms: 1,
  },
  {
    id: 44,
    description: "Elegant suite with private terrace",
    price: 350,
    location: "Savannah",
    totalbeds: 3,
    totalrooms: 2,
  },
  {
    id: 45,
    description: "Urban studio with modern decor",
    price: 120,
    location: "Columbus",
    totalbeds: 1,
    totalrooms: 1,
  },
  {
    id: 46,
    description: "Lakeside mansion with boat rental",
    price: 800,
    location: "Lake Tahoe",
    totalbeds: 10,
    totalrooms: 7,
  },
  {
    id: 47,
    description: "Contemporary room with pool access",
    price: 180,
    location: "San Antonio",
    totalbeds: 2,
    totalrooms: 1,
  },
  {
    id: 48,
    description: "Traditional guesthouse with local charm",
    price: 140,
    location: "Charleston",
    totalbeds: 3,
    totalrooms: 2,
  },
  {
    id: 49,
    description: "Studio with mountain views",
    price: 100,
    location: "Boulder",
    totalbeds: 1,
    totalrooms: 1,
  },
  {
    id: 50,
    description: "Grand estate for large events",
    price: 1500,
    location: "Beverly Hills",
    totalbeds: 20,
    totalrooms: 15,
  },
];

export const findRoom = (id: string | undefined) => {
  const idNumber = Number(id);
  return rooms.find((entry) => entry.id === idNumber);
};
