import { Person } from "./Person";

const peopleList: Person[] = [
  {
    id: 1,
    name: "Alice Johnson",
    age: 28,
    position: "Engineer",
    heightInMiliMeters: 1650,
  },
  {
    id: 2,
    name: "Bob Smith",
    age: 35,
    position: "Manager",
    heightInMiliMeters: 1780,
  },
  {
    id: 3,
    name: "Charlie Brown",
    age: 22,
    position: "Intern",
    heightInMiliMeters: 1720,
  },
  {
    id: 4,
    name: "Diana Prince",
    age: 40,
    position: "CEO",
    heightInMiliMeters: 1600,
  },
  {
    id: 5,
    name: "Ethan Hunt",
    age: 29,
    position: "Analyst",
    heightInMiliMeters: 1750,
  },
  {
    id: 6,
    name: "Fiona Carter",
    age: 33,
    position: "Designer",
    heightInMiliMeters: 1680,
  },
  {
    id: 7,
    name: "George Miller",
    age: 45,
    position: "Director",
    heightInMiliMeters: 1820,
  },
  {
    id: 8,
    name: "Hannah Davis",
    age: 26,
    position: "HR Specialist",
    heightInMiliMeters: 1580,
  },
  {
    id: 9,
    name: "Ian Wright",
    age: 31,
    position: "Developer",
    heightInMiliMeters: 1800,
  },
  {
    id: 10,
    name: "Julia Stone",
    age: 39,
    position: "Architect",
    heightInMiliMeters: 1660,
  },
  {
    id: 11,
    name: "Kevin Lewis",
    age: 41,
    position: "Consultant",
    heightInMiliMeters: 1740,
  },
  {
    id: 12,
    name: "Laura Bennett",
    age: 30,
    position: "Accountant",
    heightInMiliMeters: 1620,
  },
  {
    id: 13,
    name: "Michael Jordan",
    age: 36,
    position: "Coach",
    heightInMiliMeters: 1920,
  },
  {
    id: 14,
    name: "Natalie Green",
    age: 25,
    position: "Writer",
    heightInMiliMeters: 1700,
  },
  {
    id: 15,
    name: "Oscar Peterson",
    age: 50,
    position: "Musician",
    heightInMiliMeters: 1760,
  },
  {
    id: 16,
    name: "Paula Mitchell",
    age: 27,
    position: "Marketing Specialist",
    heightInMiliMeters: 1640,
  },
  {
    id: 17,
    name: "Quentin Harris",
    age: 38,
    position: "Project Manager",
    heightInMiliMeters: 1780,
  },
  {
    id: 18,
    name: "Rachel Adams",
    age: 32,
    position: "Scientist",
    heightInMiliMeters: 1680,
  },
  {
    id: 19,
    name: "Sam Williams",
    age: 44,
    position: "Technician",
    heightInMiliMeters: 1700,
  },
  {
    id: 20,
    name: "Tina Cooper",
    age: 23,
    position: "Assistant",
    heightInMiliMeters: 1600,
  },
  {
    id: 21,
    name: "Ulysses Grant",
    age: 29,
    position: "Historian",
    heightInMiliMeters: 1770,
  },
  {
    id: 22,
    name: "Victoria Hale",
    age: 34,
    position: "Nurse",
    heightInMiliMeters: 1630,
  },
  {
    id: 23,
    name: "William Scott",
    age: 46,
    position: "Lawyer",
    heightInMiliMeters: 1800,
  },
  {
    id: 24,
    name: "Xavier Lopez",
    age: 37,
    position: "Translator",
    heightInMiliMeters: 1740,
  },
  {
    id: 25,
    name: "Yasmine Khan",
    age: 28,
    position: "Teacher",
    heightInMiliMeters: 1690,
  },
  {
    id: 26,
    name: "Zachary Edwards",
    age: 31,
    position: "Pilot",
    heightInMiliMeters: 1850,
  },
  {
    id: 27,
    name: "Amelia Watson",
    age: 26,
    position: "Physicist",
    heightInMiliMeters: 1640,
  },
  {
    id: 28,
    name: "Brandon Lee",
    age: 40,
    position: "Chef",
    heightInMiliMeters: 1730,
  },
  {
    id: 29,
    name: "Chloe Foster",
    age: 35,
    position: "Trainer",
    heightInMiliMeters: 1710,
  },
  {
    id: 30,
    name: "David King",
    age: 47,
    position: "Surgeon",
    heightInMiliMeters: 1820,
  },
];

export const findPerson = (searchId: number) => {
  const person = peopleList.find((entry) => entry.id === searchId);

  return person;
};

export default peopleList;
